apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: 'app=next-gen-ui'
    circleci.com/project-slug: github/ruby2001/sample-javascript-cfd 
    backstage.io/techdocs-ref: url:https://github.com/sandeepa-kv-jois/harness-core-ui
    accountIdentifier: vpCkHKsDSxK9_KYfjCTMKA
    orgIdentifier: default
    projectIdentifier: UICore
  name: ng-ui
spec:
  lifecycle: production
  system: CD-NG 
  owner: ui-team
  type: service
  dependsOn: 
    - Component:ui-core-lib
  consumesApis: 
    - swagger
  
